@baseUrl = http://localhost:3000
@api = {{baseUrl}}/api
@folderId = 757f60bc-cc6c-44c4-9824-c7b95c145e64
@fileId = 757f60bc-cc6c-44c4-9824-c7b95c145e64

### Upload File
POST {{api}}/files/upload
Content-Type: multipart/form-data

{
  "file": "@/path/to/your/file.txt",
  "folderId": "{{folderId}}"
}

### Get Files
GET {{api}}/files?folderId={{folderId}}

### Preview File
GET {{api}}/files/{{fileId}}/preview

### Rename File
PATCH {{api}}/files/{{fileId}}
Content-Type: application/json

{
  "name": "new-file-name.txt"
}

### Move File
PATCH {{api}}/files/{{fileId}}/move
Content-Type: application/json

{
  "folderId": "{{folderId}}"
}

### Soft Delete File
DELETE {{api}}/files/{{fileId}}/soft-delete  

### Restore File
POST {{api}}/files/{{fileId}}/restore