@baseUrl = http://localhost:3000
@api = {{baseUrl}}/api
@folderId = 757f60bc-cc6c-44c4-9824-c7b95c145e64

### Upload File
POST {{api}}/files/upload
Content-Type: multipart/form-data

{
  "file": "@/path/to/your/file.txt",
  "folderId": "{{folderId}}"
}

### Get Files
GET {{api}}/files?folderId={{folderId}}