@baseUrl = http://localhost:3000
@api = {{baseUrl}}/api
@folderId = 757f60bc-cc6c-44c4-9824-c7b95c145e64

### Create Folder
POST {{api}}/folders
Content-Type: application/json

{
  "name": "Hari",
  "parentId": null
}

#### Get Folders
GET {{api}}/folders?parentId={{folderId}}

#### Get Folder Details
GET {{api}}/folders/{{folderId}}

#### Rename Folder
PATCH {{api}}/folders/{{folderId}}
Content-Type: application/json

{
  "name": "New Folder Name"
}

#### Move Folder
PATCH {{api}}/folders/{{folderId}}/move
Content-Type: application/json

{
  "parentId": "new-parent-folder-id"
}

#### Soft Delete Folder
DELETE  {{api}}/folders/{{folderId}}/soft-delete

#### Restore Folder
PATCH {{api}}/folders/{{folderId}}/restore